RECORDINGS_BUCKET = "zoom-recording-files"

NOTIFICATIONS_TOPIC = "notifications"
METRIC_NAMESPACE = "log-metrics"

SCHEDULE_TABLE = "schedule"
PIPELINE_STATUS_TABLE = "pipeline-status"
RECORDING_EVENTS_TABLE = "recording-events"

DOWNLOAD_QUEUE = "download"
DOWNLOAD_DLQ = "download-dlq"
UPLOAD_QUEUE = "upload.fifo"
UPLOAD_DLQ = "upload-dlq.fifo"
QUEUES = [DOWNLOAD_QUEUE, DOWNLOAD_DLQ, UPLOAD_QUEUE, UPLOAD_DLQ]

ON_DEMAND_FUNCTION = "zoom_on_demand"
WEBHOOK_FUNCTION = "zoom_webhook"
DOWNLOAD_FUNCTION = "zoom_downloader"
UPLOAD_FUNCTION = "zoom_uploader"
LOG_NOTIFICATION_FUNCTION = "zoom_log_notifications"
SCHEDULE_UPDATE_FUNCTION = "schedule_update"
STATUS_FUNCTION = "status_query"
SLACK_FUNCTION = "slack"
FUNCTIONS = [
    ON_DEMAND_FUNCTION,
    WEBHOOK_FUNCTION,
    DOWNLOAD_FUNCTION,
    UPLOAD_FUNCTION,
    LOG_NOTIFICATION_FUNCTION,
    SCHEDULE_UPDATE_FUNCTION,
    STATUS_FUNCTION,
    SLACK_FUNCTION,
]

REST_API = "api"
API_STAGE = "live"
WEBHOOK_ENDPOINT = "webhook"
ON_DEMAND_ENDPOINT = "ingest"
SCHEDULE_UPDATE_ENDPOINT = "schedule"
STATUS_ENDPOINT = "status"
SLACK_ENDPOINT = "slack"

LAMBDA_RELEASE_ALIAS = "live"
