name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: './requirements/dev.txt'

      - name: Install libraries
        run: pip install -r requirements/dev.txt

      - name: Run tests
        run: tox

  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: './requirements/dev.txt'

      - name: Install libraries
        run: pip install -r requirements/dev.txt

      - name: lint
        run: flake8

      - name: format
        run: black --check .
